name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # ajuste conforme o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: SSH into EC2 and update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd CalmoMilla-FrontEnd
            git pull
            # Comandos adicionais, se necessário
            # Reiniciar o servidor, por exemplo
